/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/views/**/*.ejs'],
  theme: {
    extend: {
      colors: {
        surface: {
          DEFAULT: '#f8f9ff',
          dim: '#ccdbf4',
          bright: '#f8f9ff',
          container: {
            lowest: '#ffffff',
            low: '#eff4ff',
            DEFAULT: '#e5eeff',
            high: '#dce9ff',
            highest: '#d4e4fc',
          },
          variant: '#d4e4fc',
        },
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d4e4fc',
        'surface-variant': '#d4e4fc',
        'surface-bright': '#f8f9ff',
        'surface-dim': '#ccdbf4',
        primary: {
          DEFAULT: '#002045',
          container: '#1a365d',
          fixed: '#d6e3ff',
          'fixed-dim': '#adc7f7',
          'on-fixed': '#001b3c',
          'on-fixed-variant': '#2d476f',
        },
        secondary: {
          DEFAULT: '#0a6c44',
          container: '#9ff5c1',
          fixed: '#9ff5c1',
          'fixed-dim': '#83d8a6',
          'on-fixed': '#002111',
          'on-fixed-variant': '#005231',
        },
        tertiary: {
          DEFAULT: '#371800',
          container: '#572900',
          fixed: '#ffdcc5',
          'fixed-dim': '#ffb783',
          'on-fixed': '#301400',
          'on-fixed-variant': '#703700',
        },
        'on-surface': '#0d1c2e',
        'on-surface-variant': '#43474e',
        'on-primary': '#ffffff',
        'on-primary-container': '#86a0cd',
        'on-primary-fixed': '#001b3c',
        'on-primary-fixed-variant': '#2d476f',
        'primary-fixed': '#d6e3ff',
        'primary-fixed-dim': '#adc7f7',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#167249',
        'on-secondary-fixed': '#002111',
        'secondary-fixed': '#9ff5c1',
        'secondary-fixed-dim': '#83d8a6',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#e88532',
        'on-tertiary-fixed': '#301400',
        'tertiary-fixed': '#ffdcc5',
        'on-background': '#0d1c2e',
        outline: {
          DEFAULT: '#74777f',
          variant: '#c4c6cf',
        },
        error: {
          DEFAULT: '#ba1a1a',
          container: '#ffdad6',
          'on-container': '#93000a',
        },
        'on-error': '#ffffff',
        background: '#f8f9ff',
        'inverse-surface': '#223144',
        'inverse-on-surface': '#eaf1ff',
        'inverse-primary': '#adc7f7',
        'surface-tint': '#455f88',
      },
      fontFamily: {
        display: ['Montserrat', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        display: ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '34px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '30px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '400' }],
      },
      spacing: {
        gutter: '24px',
        xl: '80px',
        lg: '48px',
        md: '24px',
        sm: '12px',
        'margin-mobile': '16px',
      },
      maxWidth: {
        content: '75rem',
        site: '75rem',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
      },
      boxShadow: {
        card: '0 4px 20px rgba(26, 54, 93, 0.08)',
      },
    },
  },
  plugins: [],
};
