export const cmsEntityConfigs = {
  pages: {
    key: 'pages',
    label: 'Pages',
    singular: 'Page',
    adminBase: '/admin/cms/pages',
    slugField: 'slug',
    listColumns: [
      { key: 'title', label: 'Title' },
      { key: 'slug', label: 'Slug' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true, colspan: 2 },
      { name: 'slug', label: 'URL Slug', type: 'text', required: true, colspan: 2 },
      { name: 'body', label: 'Body', type: 'textarea', colspan: 2, rows: 8 },
      { name: 'meta_title', label: 'Meta Title', type: 'text', colspan: 2 },
      { name: 'meta_description', label: 'Meta Description', type: 'textarea', colspan: 2 },
      { name: 'status', label: 'Status', type: 'select', options: [{ value: 'draft', label: 'Draft' }, { value: 'published', label: 'Published' }] },
    ],
    uploads: [],
  },
  homepage: {
    key: 'homepage',
    label: 'Homepage Sections',
    singular: 'Homepage Section',
    adminBase: '/admin/cms/homepage',
    slugField: 'section_key',
    listColumns: [
      { key: 'section_key', label: 'Section Key' },
      { key: 'title', label: 'Title' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    fields: [
      { name: 'section_key', label: 'Section Key', type: 'text', required: true, hint: 'e.g. hero, about, cta' },
      { name: 'title', label: 'Title', type: 'text', colspan: 2 },
      { name: 'subtitle', label: 'Subtitle / Eyebrow', type: 'text', colspan: 2 },
      { name: 'body', label: 'Body', type: 'textarea', colspan: 2, rows: 6 },
      { name: 'cta_label', label: 'CTA Label', type: 'text' },
      { name: 'cta_url', label: 'CTA URL', type: 'text' },
      { name: 'sort_order', label: 'Sort Order', type: 'number' },
      { name: 'status', label: 'Status', type: 'select', options: [{ value: 'draft', label: 'Draft' }, { value: 'published', label: 'Published' }] },
    ],
    uploads: [{ field: 'image', target: 'image_url', folder: 'homepage', bucket: 'tenant-media' }],
  },
  programs: {
    key: 'programs',
    label: 'Programs',
    singular: 'Program',
    adminBase: '/admin/cms/programs',
    slugField: 'slug',
    listColumns: [
      { key: 'title', label: 'Title' },
      { key: 'category', label: 'Category' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true, colspan: 2 },
      { name: 'slug', label: 'Slug', type: 'text', required: true, colspan: 2 },
      { name: 'category', label: 'Category', type: 'text' },
      { name: 'sort_order', label: 'Sort Order', type: 'number' },
      { name: 'summary', label: 'Summary', type: 'textarea', colspan: 2 },
      { name: 'body', label: 'Detail Body', type: 'textarea', colspan: 2, rows: 6 },
      { name: 'progress', label: 'Progress %', type: 'number' },
      { name: 'progress_label', label: 'Progress Label', type: 'text' },
      { name: 'objectives', label: 'Objectives (one per line)', type: 'textarea', colspan: 2, rows: 4, jsonArray: true },
      { name: 'outcomes', label: 'Outcomes JSON', type: 'textarea', colspan: 2, rows: 4, jsonOutcomes: true },
      { name: 'status', label: 'Status', type: 'select', options: [{ value: 'draft', label: 'Draft' }, { value: 'published', label: 'Published' }] },
    ],
    uploads: [
      { field: 'image', target: 'image_url', folder: 'programs', bucket: 'tenant-media' },
      { field: 'hero_image', target: 'hero_image_url', folder: 'programs', bucket: 'tenant-media' },
    ],
  },
  news: {
    key: 'news',
    label: 'News Posts',
    singular: 'News Post',
    adminBase: '/admin/cms/news',
    slugField: 'slug',
    listColumns: [
      { key: 'title', label: 'Title' },
      { key: 'category', label: 'Category' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true, colspan: 2 },
      { name: 'slug', label: 'Slug', type: 'text', required: true, colspan: 2 },
      { name: 'category', label: 'Category', type: 'text' },
      { name: 'author', label: 'Author', type: 'text' },
      { name: 'featured', label: 'Featured', type: 'select', options: [{ value: 'false', label: 'No' }, { value: 'true', label: 'Yes' }] },
      { name: 'excerpt', label: 'Excerpt', type: 'textarea', colspan: 2 },
      { name: 'body', label: 'Body', type: 'textarea', colspan: 2, rows: 8 },
      { name: 'status', label: 'Status', type: 'select', options: [{ value: 'draft', label: 'Draft' }, { value: 'published', label: 'Published' }] },
    ],
    uploads: [{ field: 'image', target: 'image_url', folder: 'news', bucket: 'tenant-media' }],
  },
  events: {
    key: 'events',
    label: 'Events',
    singular: 'Event',
    adminBase: '/admin/cms/events',
    slugField: 'slug',
    listColumns: [
      { key: 'title', label: 'Title' },
      { key: 'event_date', label: 'Date' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true, colspan: 2 },
      { name: 'slug', label: 'Slug', type: 'text', required: true, colspan: 2 },
      { name: 'event_date', label: 'Event Date', type: 'date', required: true },
      { name: 'event_time', label: 'Event Time', type: 'text' },
      { name: 'location', label: 'Location', type: 'text', colspan: 2 },
      { name: 'summary', label: 'Summary', type: 'textarea', colspan: 2 },
      { name: 'featured', label: 'Featured', type: 'select', options: [{ value: 'false', label: 'No' }, { value: 'true', label: 'Yes' }] },
      { name: 'status', label: 'Status', type: 'select', options: [{ value: 'draft', label: 'Draft' }, { value: 'published', label: 'Published' }] },
    ],
    uploads: [],
  },
  gallery: {
    key: 'gallery',
    label: 'Gallery',
    singular: 'Gallery Item',
    adminBase: '/admin/cms/gallery',
    listColumns: [
      { key: 'title', label: 'Title' },
      { key: 'category', label: 'Category' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true, colspan: 2 },
      { name: 'category', label: 'Category', type: 'text' },
      { name: 'sort_order', label: 'Sort Order', type: 'number' },
      {
        name: 'is_child_related',
        label: 'Child-Related Media',
        type: 'select',
        options: [
          { value: 'false', label: 'No' },
          { value: 'true', label: 'Yes — requires safeguarding approval' },
        ],
        hint: 'Child-related images must be approved before publishing.',
      },
      {
        name: 'consent_status',
        label: 'Consent Status',
        type: 'select',
        options: [
          { value: 'unknown', label: 'Unknown' },
          { value: 'pending', label: 'Pending' },
          { value: 'recorded', label: 'Recorded' },
          { value: 'missing', label: 'Missing' },
          { value: 'not_required', label: 'Not Required' },
        ],
      },
      {
        name: 'submit_for_review',
        label: 'Submit for Review',
        type: 'select',
        options: [
          { value: 'false', label: 'No' },
          { value: 'true', label: 'Yes — queue for media approval' },
        ],
      },
      { name: 'status', label: 'Status', type: 'select', options: [{ value: 'draft', label: 'Draft' }, { value: 'published', label: 'Published' }] },
    ],
    uploads: [{ field: 'image', target: 'image_url', folder: 'gallery', bucket: 'tenant-media' }],
  },
  resources: {
    key: 'resources',
    label: 'Resources',
    singular: 'Resource',
    adminBase: '/admin/cms/resources',
    slugField: 'slug',
    listColumns: [
      { key: 'title', label: 'Title' },
      { key: 'file_type', label: 'Type' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true, colspan: 2 },
      { name: 'slug', label: 'Slug', type: 'text', required: true, colspan: 2 },
      { name: 'description', label: 'Description', type: 'textarea', colspan: 2 },
      { name: 'file_type', label: 'File Type', type: 'text' },
      { name: 'file_size', label: 'File Size', type: 'text' },
      { name: 'status', label: 'Status', type: 'select', options: [{ value: 'draft', label: 'Draft' }, { value: 'published', label: 'Published' }] },
    ],
    uploads: [{ field: 'file', target: 'file_url', folder: 'publications', bucket: 'resources' }],
  },
};

export default cmsEntityConfigs;
